#!/bin/bash

# Get all interfaces and their IPv4 addresses
interfaces=$(ip -4 addr show | grep inet | awk '{print $2}')

# Print the list of IPv4 addresses
echo "Active IPv4 addresses:"
echo "$interfaces"

